/* ═══════════════ i18n.js — Translations, seed data, COL data, REGIONS, FAMS ═══════════════ */

// ═══════════════ DATA
export const REGIONS=[
{id:"we",name:"Western Europe",emoji:"🏰"},{id:"ee",name:"Eastern Europe",emoji:"🏛"},
{id:"na",name:"North America",emoji:"🗽"},{id:"la",name:"Latin America",emoji:"🌎"},
{id:"sea",name:"Southeast Asia",emoji:"🌴"},{id:"ea",name:"East Asia",emoji:"🏯"},
{id:"me",name:"Middle East",emoji:"🕌"},{id:"sa",name:"South Asia",emoji:"🕉"},
{id:"ca",name:"Central Asia & Caucasus",emoji:"⛰"},{id:"oc",name:"Oceania",emoji:"🦘"},
{id:"af",name:"Africa",emoji:"🌍"}];
export const FAMS=[
{id:"solo",lk:"solo",persons:1,rentMul:1,utilMul:1},
{id:"couple",lk:"couple",persons:2,rentMul:1.3,utilMul:1.2},
{id:"fam1",lk:"kid1",persons:3,rentMul:1.6,utilMul:1.3},
{id:"fam2",lk:"kid2",persons:4,rentMul:1.8,utilMul:1.4},
{id:"fam3",lk:"kid3",persons:5,rentMul:2.0,utilMul:1.5},
{id:"fam4",lk:"kid4",persons:6,rentMul:2.2,utilMul:1.6}];
export function colTot(c,fam){const f=FAMS.find(p=>p.id===fam)||FAMS[0];return Math.round(c.rent*f.rentMul+(c.food+c.transport+c.other)*(f.persons*.65+.35)+c.utilities*f.utilMul+c.health*f.persons)}
export const COL=[
{code:"LIS",city:"Lisbon",country:"Portugal",flag:"🇵🇹",region:"we",rent:1000,food:350,transport:60,utilities:130,health:50,other:200,inf:3.5,tax:20,notes:"D8 DN visa. NHR regime can lower tax."},
{code:"BCN",city:"Barcelona",country:"Spain",flag:"🇪🇸",region:"we",rent:1100,food:400,transport:55,utilities:140,health:60,other:250,inf:3.5,tax:24,notes:"Beckham law: 24% flat for 6 yrs."},
{code:"BER",city:"Berlin",country:"Germany",flag:"🇩🇪",region:"we",rent:1100,food:400,transport:90,utilities:250,health:200,other:260,inf:2.5,tax:30,notes:"Freelance visa. Progressive tax."},
{code:"AMS",city:"Amsterdam",country:"Netherlands",flag:"🇳🇱",region:"we",rent:1600,food:420,transport:80,utilities:200,health:130,other:280,inf:2.8,tax:33,notes:"30% ruling can reduce taxable income."},
{code:"PAR",city:"Paris",country:"France",flag:"🇫🇷",region:"we",rent:1300,food:450,transport:80,utilities:180,health:50,other:300,inf:2.5,tax:30,notes:"Talent passport. High social charges."},
{code:"ZUR",city:"Zürich",country:"Switzerland",flag:"🇨🇭",region:"we",rent:2200,food:650,transport:120,utilities:200,health:350,other:400,inf:1.5,tax:22,notes:"Low tax but very high cost."},
{code:"DUB",city:"Dublin",country:"Ireland",flag:"🇮🇪",region:"we",rent:1800,food:400,transport:100,utilities:200,health:60,other:280,inf:2.5,tax:32,notes:"English-speaking EU hub."},
{code:"MIL",city:"Milan",country:"Italy",flag:"🇮🇹",region:"we",rent:1100,food:400,transport:50,utilities:180,health:60,other:240,inf:2.5,tax:7,notes:"7% flat tax for new residents."},
{code:"SPL",city:"Split",country:"Croatia",flag:"🇭🇷",region:"we",rent:750,food:350,transport:40,utilities:140,health:50,other:200,inf:3.0,tax:0,notes:"DN visa: 0% tax on foreign income."},
{code:"WAR",city:"Warsaw",country:"Poland",flag:"🇵🇱",region:"ee",rent:750,food:320,transport:35,utilities:160,health:50,other:200,inf:4.0,tax:19,notes:"19% flat for self-employed. EU."},
{code:"BUD",city:"Budapest",country:"Hungary",flag:"🇭🇺",region:"ee",rent:650,food:300,transport:30,utilities:140,health:40,other:180,inf:5.0,tax:15,notes:"15% flat income tax."},
{code:"SOF",city:"Sofia",country:"Bulgaria",flag:"🇧🇬",region:"ee",rent:500,food:280,transport:30,utilities:100,health:40,other:150,inf:3.5,tax:10,notes:"10% flat tax. EU. Very affordable."},
{code:"BUC",city:"Bucharest",country:"Romania",flag:"🇷🇴",region:"ee",rent:550,food:300,transport:30,utilities:120,health:40,other:170,inf:4.5,tax:10,notes:"10% flat. Fastest EU internet."},
{code:"PRG",city:"Prague",country:"Czechia",flag:"🇨🇿",region:"ee",rent:800,food:330,transport:30,utilities:160,health:50,other:200,inf:3.0,tax:23,notes:"Zivno visa for freelancers."},
{code:"TAL",city:"Tallinn",country:"Estonia",flag:"🇪🇪",region:"ee",rent:700,food:350,transport:40,utilities:180,health:50,other:220,inf:3.5,tax:20,notes:"e-Residency. 20% flat."},
{code:"BEL",city:"Belgrade",country:"Serbia",flag:"🇷🇸",region:"ee",rent:500,food:280,transport:25,utilities:100,health:40,other:160,inf:5.0,tax:10,notes:"10% flat. 1yr visa-free."},
{code:"NYC",city:"New York",country:"USA",flag:"🇺🇸",region:"na",rent:2800,food:650,transport:130,utilities:200,health:500,other:500,inf:3.0,tax:32,notes:"Fed + state + city tax. HCOL."},
{code:"AUS",city:"Austin",country:"USA",flag:"🇺🇸",region:"na",rent:1600,food:500,transport:150,utilities:180,health:450,other:350,inf:3.5,tax:24,notes:"No state income tax."},
{code:"MIA",city:"Miami",country:"USA",flag:"🇺🇸",region:"na",rent:2000,food:550,transport:150,utilities:200,health:480,other:400,inf:3.5,tax:24,notes:"No state income tax. Crypto hub."},
{code:"VAN",city:"Vancouver",country:"Canada",flag:"🇨🇦",region:"na",rent:1800,food:450,transport:100,utilities:150,health:0,other:350,inf:3.0,tax:28,notes:"Free healthcare. Beautiful."},
{code:"TOR",city:"Toronto",country:"Canada",flag:"🇨🇦",region:"na",rent:1700,food:420,transport:110,utilities:160,health:0,other:320,inf:3.0,tax:28,notes:"Diverse. Free healthcare."},
{code:"CDM",city:"Mexico City",country:"Mexico",flag:"🇲🇽",region:"la",rent:600,food:280,transport:40,utilities:60,health:50,other:180,inf:5.0,tax:15,notes:"Temp resident visa. US timezone."},
{code:"MDE",city:"Medellín",country:"Colombia",flag:"🇨🇴",region:"la",rent:500,food:250,transport:30,utilities:70,health:50,other:150,inf:5.5,tax:0,notes:"DN visa. Foreign income untaxed 5yr."},
{code:"BA",city:"Buenos Aires",country:"Argentina",flag:"🇦🇷",region:"la",rent:400,food:220,transport:15,utilities:30,health:50,other:130,inf:50.0,tax:0,notes:"Very cheap in USD. High local inflation."},
{code:"SP",city:"São Paulo",country:"Brazil",flag:"🇧🇷",region:"la",rent:500,food:250,transport:40,utilities:70,health:80,other:160,inf:5.0,tax:15,notes:"DN visa. Largest LatAm economy."},
{code:"PLY",city:"Playa del Carmen",country:"Mexico",flag:"🇲🇽",region:"la",rent:700,food:300,transport:30,utilities:70,health:50,other:180,inf:5.0,tax:15,notes:"Caribbean beach + US timezone."},
{code:"BKK",city:"Bangkok",country:"Thailand",flag:"🇹🇭",region:"sea",rent:500,food:250,transport:50,utilities:80,health:40,other:150,inf:2.5,tax:0,notes:"Foreign income not remitted = untaxed."},
{code:"CMI",city:"Chiang Mai",country:"Thailand",flag:"🇹🇭",region:"sea",rent:350,food:250,transport:40,utilities:70,health:40,other:120,inf:2.5,tax:0,notes:"OG nomad city. Under $1k/mo."},
{code:"BAL",city:"Bali",country:"Indonesia",flag:"🇮🇩",region:"sea",rent:450,food:220,transport:40,utilities:60,health:30,other:140,inf:3.5,tax:0,notes:"DN visa. Foreign income untaxed."},
{code:"DAN",city:"Da Nang",country:"Vietnam",flag:"🇻🇳",region:"sea",rent:400,food:200,transport:30,utilities:50,health:30,other:100,inf:3.5,tax:0,notes:"Beach city. Tourist visa = no tax."},
{code:"HCM",city:"Ho Chi Minh",country:"Vietnam",flag:"🇻🇳",region:"sea",rent:450,food:220,transport:35,utilities:55,health:30,other:120,inf:3.5,tax:0,notes:"Energetic city. Great coffee."},
{code:"KUL",city:"Kuala Lumpur",country:"Malaysia",flag:"🇲🇾",region:"sea",rent:500,food:220,transport:40,utilities:60,health:40,other:140,inf:3.0,tax:0,notes:"Foreign-sourced income exempt."},
{code:"TYO",city:"Tokyo",country:"Japan",flag:"🇯🇵",region:"ea",rent:1000,food:400,transport:100,utilities:150,health:80,other:250,inf:2.0,tax:20,notes:"Resident taxed worldwide."},
{code:"SEL",city:"Seoul",country:"South Korea",flag:"🇰🇷",region:"ea",rent:800,food:380,transport:60,utilities:130,health:60,other:220,inf:2.5,tax:19,notes:"Fast internet. 19% flat."},
{code:"TPE",city:"Taipei",country:"Taiwan",flag:"🇹🇼",region:"ea",rent:600,food:300,transport:40,utilities:80,health:30,other:160,inf:2.0,tax:18,notes:"Gold Card program."},
{code:"DXB",city:"Dubai",country:"UAE",flag:"🇦🇪",region:"me",rent:1800,food:500,transport:180,utilities:180,health:200,other:400,inf:2.5,tax:0,notes:"0% income tax. DN visa."},
{code:"IST",city:"Istanbul",country:"Turkey",flag:"🇹🇷",region:"me",rent:550,food:280,transport:40,utilities:80,health:50,other:150,inf:40.0,tax:15,notes:"Volatile lira. Often untaxed."},
{code:"BLR",city:"Bangalore",country:"India",flag:"🇮🇳",region:"sa",rent:300,food:150,transport:25,utilities:40,health:30,other:80,inf:5.0,tax:20,notes:"India's tech capital."},
{code:"GOA",city:"Goa",country:"India",flag:"🇮🇳",region:"sa",rent:350,food:170,transport:30,utilities:45,health:30,other:100,inf:5.0,tax:20,notes:"Beach lifestyle. Nomad community."},
{code:"TBS",city:"Tbilisi",country:"Georgia",flag:"🇬🇪",region:"ca",rent:500,food:250,transport:30,utilities:60,health:50,other:130,inf:4.0,tax:1,notes:"1% small biz. 1yr visa-free."},
{code:"YER",city:"Yerevan",country:"Armenia",flag:"🇦🇲",region:"ca",rent:400,food:220,transport:25,utilities:50,health:40,other:110,inf:4.0,tax:10,notes:"IT: 10% rate. Growing scene."},
{code:"ALA",city:"Almaty",country:"Kazakhstan",flag:"🇰🇿",region:"ca",rent:500,food:250,transport:30,utilities:70,health:40,other:130,inf:8.0,tax:10,notes:"10% flat. Mountains."},
{code:"SYD",city:"Sydney",country:"Australia",flag:"🇦🇺",region:"oc",rent:2000,food:500,transport:120,utilities:180,health:100,other:350,inf:3.0,tax:30,notes:"High QoL. Taxed worldwide."},
{code:"AKL",city:"Auckland",country:"New Zealand",flag:"🇳🇿",region:"oc",rent:1400,food:420,transport:100,utilities:160,health:0,other:280,inf:3.0,tax:30,notes:"Free healthcare."},
{code:"CPT",city:"Cape Town",country:"South Africa",flag:"🇿🇦",region:"af",rent:600,food:250,transport:50,utilities:80,health:60,other:150,inf:5.5,tax:18,notes:"Foreign income exemption ~$1M."}
];

// ═══════════════ i18n
export const LANG=(new URLSearchParams(location.search).get('lang')||'en').toLowerCase();
export const I18N={
en:{pillars:'Net Worth · Forecast · Relocate',relocHd:'Where can you afford to live?',liqHd:'Liquid Assets',illHd:'Illiquid Assets',revHd:'Monthly Revenue',costHd:'Monthly Living Costs',ievHd:'Income Events',eevHd:'Expense Events',liqHint:'Each asset compounds at its own rate. The <b>primary</b> account receives all income. Expenses deduct from primary first — if depleted, they cascade to the next asset down.',illHint:'Real estate, vehicles — things that take time to sell.',ievHint:'One-time cash income, or sell an owned asset at its appreciated value.',eevHint:'One-time expenses, or buy an asset that appreciates/depreciates.',none:'None yet',now:'now',inMo:'in {m} mo',inYr:'in {y} yr',inYrMo:'in {y} yr {m} mo',moS:'m',yrS:'y',curNet:'Current Net Worth',netIn:'Net Worth in',liquid:'Liquid',illiquid:'Illiquid',total:'Total',family:'Family',taxRate:'Your tax rate',region:'Region',afford:'cities you can afford',mo:'/mo',rent:'Rent',food:'Food',transport:'Transport',util:'Utilities',health:'Health',other:'Other',tax:'Tax',inf:'Inflation',primary:'PRIMARY',add:'+ Add',del:'×',name:'Name',value:'Value',returnYr:'Return/yr',appYr:'Appr./yr',perMo:'$/month',growthYr:'Growth/yr',infYr:'Inflation/yr',link:'Link',starts:'Starts',ends:'Ends',amount:'Amount',from:'From',to:'To',growth:'Growth %',linked:'Link',type:'Type',date:'Date',when:'When',nameAsset:'Name / Asset',apprDepr:'Appr./Depr.',sell:'Sell',sellAsset:'Sell asset',cash:'Cash',expense:'Expense',buy:'Buy',buyAsset:'Buy asset',solo:'Solo',couple:'Couple',moneyIn:'Money in',moneyOut:'Money out',invReturns:'Investment returns',returns:'returns',incomeTag:'income',soldTag:'sold',boughtTag:'bought',spentTag:'spent',ownedTag:'owned',liqAssets:'Liquid assets',illAssets:'Illiquid assets',by:'By',debt:'Debt',debtTag:'debt',balance:'Balance',rate:'Rate',pmtMo:'Payment/mo',debtRemain:'remaining',debts:'Debts',loanOut:'Loan out',loanOutTag:'receivable',receivables:'Receivables',household:'Household',kid1:'+1 kid',kid2:'+2 kids',kid3:'+3 kids',kid4:'+4 kids',yourTax:'Your current tax',incomeAfterTax:'income {inc}/mo → {aft}/mo after tax',canAfford:'Can afford',cantAfford:"Can't afford",affordLine:'affordability line',afterTaxInc:'After-tax income',taxSavings:'Tax savings',taxIncrease:'Tax increase',netSurplus:'Net surplus',savingsRate:'Savings Rate',deficit:'Deficit',localInf:'Local inflation',sameTax:'same',estimates:'Estimates. Tax = effective rate on gross income. Surplus = after-tax income − local costs.'},
es:{pillars:'Patrimonio · Pronóstico · Reubicación',relocHd:'¿Dónde puedes vivir?',liqHd:'Activos Líquidos',illHd:'Activos Ilíquidos',revHd:'Ingresos Mensuales',costHd:'Gastos Mensuales',ievHd:'Eventos de Ingreso',eevHd:'Eventos de Gasto',liqHint:'Cada activo crece a su propia tasa. La cuenta <b>principal</b> recibe todos los ingresos. Los gastos se deducen primero de la cuenta principal — si se agota, pasan al siguiente activo.',illHint:'Inmuebles, vehículos — bienes que tardan en venderse.',ievHint:'Ingreso único en efectivo, o vender un activo a su valor apreciado.',eevHint:'Gasto único, o comprar un activo que se aprecia/deprecia.',none:'Ninguno',now:'ahora',inMo:'en {m} mes',inYr:'en {y} año',inYrMo:'en {y} año {m} mes',moS:'m',yrS:'a',curNet:'Patrimonio Actual',netIn:'Patrimonio en',liquid:'Líquido',illiquid:'Ilíquido',total:'Total',family:'Familia',taxRate:'Tu tasa impositiva',region:'Región',afford:'ciudades accesibles',mo:'/mes',rent:'Alquiler',food:'Comida',transport:'Transporte',util:'Servicios',health:'Salud',other:'Otros',tax:'Impuesto',inf:'Inflación',primary:'PRINCIPAL',add:'+ Añadir',del:'×',name:'Nombre',value:'Valor',returnRate:'Retorno %',appRate:'Aprec %',amount:'Monto',from:'Desde',to:'Hasta',growth:'Crec %',linked:'Vincular',type:'Tipo',date:'Fecha',sell:'Vender activo',cash:'Efectivo',expense:'Gasto',buy:'Comprar activo',solo:'Solo',couple:'Pareja',returnYr:'Retorno/año',appYr:'Aprec./año',perMo:'$/mes',growthYr:'Crec./año',infYr:'Inflación/año',link:'Vincular',starts:'Inicio',ends:'Fin',when:'Cuándo',nameAsset:'Nombre / Activo',apprDepr:'Aprec./Depr.',sell:'Vender',buy:'Comprar',buyAsset:'Comprar activo',moneyIn:'Dinero entrante',moneyOut:'Dinero saliente',invReturns:'Rendimientos de inversión',returns:'rendimiento',incomeTag:'ingreso',soldTag:'vendido',boughtTag:'comprado',spentTag:'gastado',ownedTag:'propio',liqAssets:'Activos líquidos',illAssets:'Activos ilíquidos',by:'Para',debt:'Deuda',debtTag:'deuda',balance:'Saldo',rate:'Tasa',pmtMo:'Pago/mes',debtRemain:'restante',debts:'Deudas',loanOut:'Préstamo',loanOutTag:'por cobrar',receivables:'Por cobrar',household:'Hogar',kid1:'+1 hijo',kid2:'+2 hijos',kid3:'+3 hijos',kid4:'+4 hijos',yourTax:'Tu impuesto actual',incomeAfterTax:'ingreso {inc}/mes → {aft}/mes después de impuestos',canAfford:'Accesible',cantAfford:'No accesible',affordLine:'línea de accesibilidad',afterTaxInc:'Ingreso neto',taxSavings:'Ahorro fiscal',taxIncrease:'Aumento fiscal',netSurplus:'Excedente neto',savingsRate:'Tasa de ahorro',deficit:'Déficit',localInf:'Inflación local',sameTax:'igual',estimates:'Estimaciones. Impuesto = tasa efectiva sobre ingreso bruto. Excedente = ingreso neto − costos locales.'},
fr:{pillars:'Patrimoine · Prévision · Relocalisation',relocHd:'Où pouvez-vous vivre?',liqHd:'Actifs Liquides',illHd:'Actifs Illiquides',revHd:'Revenus Mensuels',costHd:'Dépenses Mensuelles',ievHd:'Événements de Revenu',eevHd:'Événements de Dépense',liqHint:'Chaque actif croît à son propre taux. Le compte <b>principal</b> reçoit tous les revenus. Les dépenses sont d\'abord déduites du compte principal — s\'il est épuisé, elles passent à l\'actif suivant.',illHint:'Immobilier, véhicules — actifs difficiles à vendre rapidement.',ievHint:'Revenu ponctuel ou vente d\'un actif.',eevHint:'Dépense ponctuelle ou achat d\'un actif.',none:'Aucun',now:'maintenant',inMo:'dans {m} mois',inYr:'dans {y} an',inYrMo:'dans {y} an {m} mois',moS:'m',yrS:'a',curNet:'Patrimoine Actuel',netIn:'Patrimoine dans',liquid:'Liquide',illiquid:'Illiquide',total:'Total',family:'Famille',taxRate:'Votre taux d\'imposition',region:'Région',afford:'villes accessibles',mo:'/mois',rent:'Loyer',food:'Nourriture',transport:'Transport',util:'Services',health:'Santé',other:'Autres',tax:'Impôt',inf:'Inflation',primary:'PRINCIPAL',add:'+ Ajouter',del:'×',name:'Nom',value:'Valeur',returnRate:'Rend %',appRate:'Appr %',amount:'Montant',from:'De',to:'À',growth:'Crois %',linked:'Lier',type:'Type',date:'Date',sell:'Vendre actif',cash:'Espèces',expense:'Dépense',buy:'Acheter actif',solo:'Solo',couple:'Couple',returnYr:'Rend./an',appYr:'Appr./an',perMo:'€/mois',growthYr:'Crois./an',infYr:'Inflation/an',link:'Lier',starts:'Début',ends:'Fin',when:'Quand',nameAsset:'Nom / Actif',apprDepr:'Appr./Dépr.',sell:'Vendre',buy:'Acheter',buyAsset:'Acheter actif',moneyIn:'Entrées',moneyOut:'Sorties',invReturns:'Rendements des investissements',returns:'rendement',incomeTag:'revenu',soldTag:'vendu',boughtTag:'acheté',spentTag:'dépensé',ownedTag:'détenu',liqAssets:'Actifs liquides',illAssets:'Actifs illiquides',by:'D\'ici',debt:'Dette',debtTag:'dette',balance:'Solde',rate:'Taux',pmtMo:'Paiement/mois',debtRemain:'restant',debts:'Dettes',loanOut:'Prêt',loanOutTag:'créance',receivables:'Créances',household:'Foyer',kid1:'+1 enfant',kid2:'+2 enfants',kid3:'+3 enfants',kid4:'+4 enfants',yourTax:'Votre taux actuel',incomeAfterTax:'revenu {inc}/mois → {aft}/mois après impôt',canAfford:'Accessible',cantAfford:'Non accessible',affordLine:'seuil',afterTaxInc:'Revenu net',taxSavings:'Économie fiscale',taxIncrease:'Hausse fiscale',netSurplus:'Excédent net',savingsRate:'Taux d\'épargne',deficit:'Déficit',localInf:'Inflation locale',sameTax:'identique',estimates:'Estimations. Impôt = taux effectif sur revenu brut. Excédent = revenu net − coûts locaux.'},
de:{pillars:'Vermögen · Prognose · Umzug',relocHd:'Wo können Sie leben?',liqHd:'Liquide Vermögenswerte',illHd:'Illiquide Vermögenswerte',revHd:'Monatliche Einnahmen',costHd:'Monatliche Lebenshaltungskosten',ievHd:'Einmalige Einnahmen',eevHd:'Einmalige Ausgaben',liqHint:'Jedes Asset wächst mit eigener Rate. Das <b>Hauptkonto</b> empfängt alle Einnahmen. Ausgaben werden zuerst vom Hauptkonto abgezogen — ist es aufgebraucht, wird das nächste Asset belastet.',illHint:'Immobilien, Fahrzeuge — schwer schnell zu verkaufen.',ievHint:'Einmaliges Einkommen oder Verkauf eines Assets.',eevHint:'Einmalige Ausgabe oder Kauf eines Assets.',none:'Keine',now:'jetzt',inMo:'in {m} Mon.',inYr:'in {y} Jahr',inYrMo:'in {y} J. {m} Mon.',moS:'M',yrS:'J',curNet:'Aktuelles Vermögen',netIn:'Vermögen in',liquid:'Liquide',illiquid:'Illiquide',total:'Gesamt',family:'Familie',taxRate:'Ihr Steuersatz',region:'Region',afford:'leistbare Städte',mo:'/Mon.',rent:'Miete',food:'Essen',transport:'Transport',util:'Nebenkosten',health:'Gesundheit',other:'Sonstiges',tax:'Steuer',inf:'Inflation',primary:'HAUPT',add:'+ Hinzufügen',del:'×',name:'Name',value:'Wert',returnRate:'Rendite %',appRate:'Wertzuwachs %',amount:'Betrag',from:'Von',to:'Bis',growth:'Wachstum %',linked:'Verknüpfen',type:'Typ',date:'Datum',sell:'Asset verkaufen',cash:'Bargeld',expense:'Ausgabe',buy:'Asset kaufen',solo:'Allein',couple:'Paar',returnYr:'Rendite/J.',appYr:'Wertzuw./J.',perMo:'€/Mon.',growthYr:'Wachstum/J.',infYr:'Inflation/J.',link:'Verknüpfen',starts:'Start',ends:'Ende',when:'Wann',nameAsset:'Name / Asset',apprDepr:'Zuw./Abw.',sell:'Verkaufen',buy:'Kaufen',buyAsset:'Asset kaufen',moneyIn:'Einnahmen',moneyOut:'Ausgaben',invReturns:'Anlagerenditen',returns:'Rendite',incomeTag:'Einkommen',soldTag:'verkauft',boughtTag:'gekauft',spentTag:'ausgegeben',ownedTag:'besessen',liqAssets:'Liquide Mittel',illAssets:'Illiquide Mittel',by:'Bis',debt:'Schuld',debtTag:'Schuld',balance:'Saldo',rate:'Zins',pmtMo:'Zahlung/Mon.',debtRemain:'verbleibend',debts:'Schulden',loanOut:'Darlehen',loanOutTag:'Forderung',receivables:'Forderungen',household:'Haushalt',kid1:'+1 Kind',kid2:'+2 Kinder',kid3:'+3 Kinder',kid4:'+4 Kinder',yourTax:'Ihr Steuersatz',incomeAfterTax:'Einkommen {inc}/Mon. → {aft}/Mon. nach Steuer',canAfford:'Leistbar',cantAfford:'Nicht leistbar',affordLine:'Leistbarkeitsgrenze',afterTaxInc:'Nettoeinkommen',taxSavings:'Steuerersparnis',taxIncrease:'Steuermehrbelastung',netSurplus:'Nettoüberschuss',savingsRate:'Sparquote',deficit:'Defizit',localInf:'Lokale Inflation',sameTax:'gleich',estimates:'Schätzungen. Steuer = effektiver Satz auf Bruttoeinkommen. Überschuss = Nettoeinkommen − lokale Kosten.'},
pt:{pillars:'Patrimônio · Previsão · Realocação',relocHd:'Onde você pode morar?',liqHd:'Ativos Líquidos',illHd:'Ativos Ilíquidos',revHd:'Receita Mensal',costHd:'Custos Mensais',ievHd:'Eventos de Receita',eevHd:'Eventos de Despesa',liqHint:'Cada ativo cresce a sua própria taxa. A conta <b>principal</b> recebe toda a renda. As despesas são deduzidas primeiro da conta principal — se esgotada, passam para o próximo ativo.',illHint:'Imóveis, veículos — bens difíceis de vender rapidamente.',ievHint:'Renda única ou venda de um ativo.',eevHint:'Despesa única ou compra de um ativo.',none:'Nenhum',now:'agora',inMo:'em {m} mês',inYr:'em {y} ano',inYrMo:'em {y} ano {m} mês',moS:'m',yrS:'a',curNet:'Patrimônio Atual',netIn:'Patrimônio em',liquid:'Líquido',illiquid:'Ilíquido',total:'Total',family:'Família',taxRate:'Sua taxa de imposto',region:'Região',afford:'cidades acessíveis',mo:'/mês',rent:'Aluguel',food:'Comida',transport:'Transporte',util:'Utilidades',health:'Saúde',other:'Outros',tax:'Imposto',inf:'Inflação',primary:'PRINCIPAL',add:'+ Adicionar',del:'×',name:'Nome',value:'Valor',returnRate:'Retorno %',appRate:'Valoriz %',amount:'Valor',from:'De',to:'Até',growth:'Cresc %',linked:'Vincular',type:'Tipo',date:'Data',sell:'Vender ativo',cash:'Dinheiro',expense:'Despesa',buy:'Comprar ativo',solo:'Solo',couple:'Casal',returnYr:'Retorno/ano',appYr:'Valoriz./ano',perMo:'$/mês',growthYr:'Cresc./ano',infYr:'Inflação/ano',link:'Vincular',starts:'Início',ends:'Fim',when:'Quando',nameAsset:'Nome / Ativo',apprDepr:'Valoriz./Depr.',sell:'Vender',buy:'Comprar',buyAsset:'Comprar ativo',moneyIn:'Entradas',moneyOut:'Saídas',invReturns:'Rendimentos de investimento',returns:'rendimento',incomeTag:'receita',soldTag:'vendido',boughtTag:'comprado',spentTag:'gasto',ownedTag:'possuído',liqAssets:'Ativos líquidos',illAssets:'Ativos ilíquidos',by:'Até',debt:'Dívida',debtTag:'dívida',balance:'Saldo',rate:'Taxa',pmtMo:'Pagamento/mês',debtRemain:'restante',debts:'Dívidas',loanOut:'Empréstimo',loanOutTag:'a receber',receivables:'A receber',household:'Família',kid1:'+1 filho',kid2:'+2 filhos',kid3:'+3 filhos',kid4:'+4 filhos',yourTax:'Seu imposto atual',incomeAfterTax:'renda {inc}/mês → {aft}/mês após impostos',canAfford:'Acessível',cantAfford:'Não acessível',affordLine:'linha de acessibilidade',afterTaxInc:'Renda líquida',taxSavings:'Economia fiscal',taxIncrease:'Aumento fiscal',netSurplus:'Excedente líquido',savingsRate:'Taxa de poupança',deficit:'Déficit',localInf:'Inflação local',sameTax:'igual',estimates:'Estimativas. Imposto = taxa efetiva sobre renda bruta. Excedente = renda líquida − custos locais.'},
ja:{pillars:'純資産 · 予測 · 移住',relocHd:'どこに住めますか？',liqHd:'流動資産',illHd:'非流動資産',revHd:'月収',costHd:'月間生活費',ievHd:'収入イベント',eevHd:'支出イベント',liqHint:'各資産は独自のレートで成長します。<b>メイン</b>口座がすべての収入を受け取ります。支出はメイン口座から先に引かれ、残高がなくなると次の資産に移ります。',illHint:'不動産、車両 — すぐに売れない資産。',ievHint:'一時的な収入または資産の売却。',eevHint:'一時的な支出または資産の購入。',none:'なし',now:'現在',inMo:'{m}ヶ月後',inYr:'{y}年後',inYrMo:'{y}年{m}ヶ月後',moS:'月',yrS:'年',curNet:'現在の純資産',netIn:'純資産（',liquid:'流動',illiquid:'非流動',total:'合計',family:'家族',taxRate:'税率',region:'地域',afford:'住める都市',mo:'/月',rent:'家賃',food:'食費',transport:'交通',util:'光熱費',health:'医療',other:'その他',tax:'税金',inf:'インフレ',primary:'メイン',add:'+ 追加',del:'×',name:'名前',value:'金額',returnRate:'利回り%',appRate:'増価%',amount:'金額',from:'開始',to:'終了',growth:'成長%',linked:'リンク',type:'種類',date:'日付',sell:'資産売却',cash:'現金',expense:'支出',buy:'資産購入',solo:'一人',couple:'二人',returnYr:'利回り/年',appYr:'増価/年',perMo:'$/月',growthYr:'成長/年',infYr:'インフレ/年',link:'リンク',starts:'開始',ends:'終了',when:'時期',nameAsset:'名前 / 資産',apprDepr:'増価/減価',sell:'売却',buy:'購入',buyAsset:'資産購入',moneyIn:'収入',moneyOut:'支出',invReturns:'投資リターン',returns:'リターン',incomeTag:'収入',soldTag:'売却',boughtTag:'購入',spentTag:'支出',ownedTag:'保有',liqAssets:'流動資産',illAssets:'非流動資産',by:'まで',debt:'借入',debtTag:'借入',balance:'残高',rate:'金利',pmtMo:'月々返済',debtRemain:'残高',debts:'借入金',loanOut:'貸出',loanOutTag:'債権',receivables:'貸出金',household:'世帯',kid1:'+1人',kid2:'+2人',kid3:'+3人',kid4:'+4人',yourTax:'現在の税率',incomeAfterTax:'収入 {inc}/月 → {aft}/月（税引後）',canAfford:'住める',cantAfford:'住めない',affordLine:'境界線',afterTaxInc:'税引後収入',taxSavings:'節税',taxIncrease:'増税',netSurplus:'余剰',savingsRate:'貯蓄率',deficit:'赤字',localInf:'現地インフレ',sameTax:'同じ',estimates:'推定値。税 = 総収入に対する実効税率。余剰 = 税引後収入 − 現地コスト。'},
zh:{pillars:'净资产 · 预测 · 搬迁',relocHd:'你能住在哪里？',liqHd:'流动资产',illHd:'非流动资产',revHd:'月收入',costHd:'月生活成本',ievHd:'收入事件',eevHd:'支出事件',liqHint:'每项资产以自己的利率增长。<b>主</b>账户接收所有收入。支出先从主账户扣除——如果用尽，会依次从下一个资产扣除。',illHint:'房产、车辆 — 不易快速出售的资产。',ievHint:'一次性收入或出售资产。',eevHint:'一次性支出或购买资产。',none:'暂无',now:'现在',inMo:'{m}个月后',inYr:'{y}年后',inYrMo:'{y}年{m}个月后',moS:'月',yrS:'年',curNet:'当前净资产',netIn:'净资产（',liquid:'流动',illiquid:'非流动',total:'总计',family:'家庭',taxRate:'你的税率',region:'地区',afford:'个可负担城市',mo:'/月',rent:'房租',food:'食物',transport:'交通',util:'水电',health:'医疗',other:'其他',tax:'税',inf:'通胀',primary:'主要',add:'+ 添加',del:'×',name:'名称',value:'金额',returnRate:'回报%',appRate:'增值%',amount:'金额',from:'从',to:'至',growth:'增长%',linked:'关联',type:'类型',date:'日期',sell:'出售资产',cash:'现金',expense:'支出',buy:'购买资产',solo:'单身',couple:'情侣',returnYr:'回报/年',appYr:'增值/年',perMo:'$/月',growthYr:'增长/年',infYr:'通胀/年',link:'关联',starts:'开始',ends:'结束',when:'时间',nameAsset:'名称 / 资产',apprDepr:'增值/贬值',sell:'出售',buy:'购买',buyAsset:'购买资产',moneyIn:'资金流入',moneyOut:'资金流出',invReturns:'投资收益',returns:'收益',incomeTag:'收入',soldTag:'已售',boughtTag:'已购',spentTag:'已支出',ownedTag:'持有',liqAssets:'流动资产',illAssets:'非流动资产',by:'截至',debt:'贷款',debtTag:'贷款',balance:'余额',rate:'利率',pmtMo:'月还款',debtRemain:'剩余',debts:'负债',loanOut:'借出',loanOutTag:'应收',receivables:'应收款',household:'家庭',kid1:'+1孩',kid2:'+2孩',kid3:'+3孩',kid4:'+4孩',yourTax:'当前税率',incomeAfterTax:'收入 {inc}/月 → {aft}/月（税后）',canAfford:'可负担',cantAfford:'不可负担',affordLine:'负担能力线',afterTaxInc:'税后收入',taxSavings:'节税',taxIncrease:'增税',netSurplus:'净盈余',savingsRate:'储蓄率',deficit:'赤字',localInf:'当地通胀',sameTax:'相同',estimates:'估算。税 = 总收入有效税率。盈余 = 税后收入 − 当地成本。'},
ko:{pillars:'순자산 · 예측 · 이주',relocHd:'어디서 살 수 있나요?',liqHd:'유동 자산',illHd:'비유동 자산',revHd:'월 수입',costHd:'월 생활비',ievHd:'수입 이벤트',eevHd:'지출 이벤트',liqHint:'각 자산은 고유한 수익률로 성장합니다. <b>기본</b> 계좌가 모든 수입을 받습니다. 지출은 기본 계좌에서 먼저 차감되며, 잔액이 부족하면 다음 자산으로 넘어갑니다.',illHint:'부동산, 차량 — 빨리 팔기 어려운 자산.',ievHint:'일시적 수입 또는 자산 매각.',eevHint:'일시적 지출 또는 자산 구매.',none:'없음',now:'현재',inMo:'{m}개월 후',inYr:'{y}년 후',inYrMo:'{y}년 {m}개월 후',moS:'월',yrS:'년',curNet:'현재 순자산',netIn:'순자산 (',liquid:'유동',illiquid:'비유동',total:'합계',family:'가족',taxRate:'세율',region:'지역',afford:'거주 가능 도시',mo:'/월',rent:'임대료',food:'식비',transport:'교통',util:'공과금',health:'의료',other:'기타',tax:'세금',inf:'인플레이션',primary:'기본',add:'+ 추가',del:'×',name:'이름',value:'금액',returnRate:'수익률%',appRate:'감정%',amount:'금액',from:'시작',to:'종료',growth:'성장%',linked:'연결',type:'유형',date:'날짜',sell:'자산 매각',cash:'현금',expense:'지출',buy:'자산 구매',solo:'1인',couple:'2인',returnYr:'수익/년',appYr:'감정/년',perMo:'$/월',growthYr:'성장/년',infYr:'인플레이션/년',link:'연결',starts:'시작',ends:'종료',when:'시기',nameAsset:'이름 / 자산',apprDepr:'감정/감가',sell:'매각',buy:'구매',buyAsset:'자산 구매',moneyIn:'수입',moneyOut:'지출',invReturns:'투자 수익',returns:'수익',incomeTag:'소득',soldTag:'매각',boughtTag:'구매',spentTag:'지출',ownedTag:'보유',liqAssets:'유동 자산',illAssets:'비유동 자산',by:'까지',debt:'부채',debtTag:'부채',balance:'잔액',rate:'이자율',pmtMo:'월상환',debtRemain:'잔여',debts:'부채',loanOut:'대출',loanOutTag:'채권',receivables:'미수금',household:'가구',kid1:'+1명',kid2:'+2명',kid3:'+3명',kid4:'+4명',yourTax:'현재 세율',incomeAfterTax:'소득 {inc}/월 → {aft}/월 세후',canAfford:'거주 가능',cantAfford:'거주 불가',affordLine:'거주 가능 경계',afterTaxInc:'세후 소득',taxSavings:'절세',taxIncrease:'세금 증가',netSurplus:'순여유',savingsRate:'저축률',deficit:'적자',localInf:'현지 인플레이션',sameTax:'동일',estimates:'추정치. 세금 = 총소득 대비 실효세율. 여유 = 세후소득 − 현지비용.'},
tr:{pillars:'Net Değer · Tahmin · Taşınma',relocHd:'Nerede yaşayabilirsiniz?',liqHd:'Likit Varlıklar',illHd:'Likit Olmayan Varlıklar',revHd:'Aylık Gelir',costHd:'Aylık Yaşam Giderleri',ievHd:'Gelir Olayları',eevHd:'Gider Olayları',liqHint:'Her varlık kendi oranında büyür. <b>Ana</b> hesap tüm geliri alır. Harcamalar önce ana hesaptan düşülür — tükenirse sıradaki varlığa geçer.',illHint:'Gayrimenkul, araçlar — hızlı satılamayan varlıklar.',ievHint:'Tek seferlik gelir veya varlık satışı.',eevHint:'Tek seferlik gider veya varlık alımı.',none:'Henüz yok',now:'şimdi',inMo:'{m} ay sonra',inYr:'{y} yıl sonra',inYrMo:'{y} yıl {m} ay sonra',moS:'a',yrS:'y',curNet:'Mevcut Net Değer',netIn:'Net Değer',liquid:'Likit',illiquid:'Likit Olmayan',total:'Toplam',family:'Aile',taxRate:'Vergi oranınız',region:'Bölge',afford:'yaşanabilir şehir',mo:'/ay',rent:'Kira',food:'Yemek',transport:'Ulaşım',util:'Faturalar',health:'Sağlık',other:'Diğer',tax:'Vergi',inf:'Enflasyon',primary:'ANA',add:'+ Ekle',del:'×',name:'Ad',value:'Değer',returnRate:'Getiri %',appRate:'Değerlenme %',amount:'Tutar',from:'Başlangıç',to:'Bitiş',growth:'Büyüme %',linked:'Bağla',type:'Tür',date:'Tarih',sell:'Varlık sat',cash:'Nakit',expense:'Gider',buy:'Varlık al',solo:'Tek',couple:'Çift',returnYr:'Getiri/yıl',appYr:'Değerl./yıl',perMo:'$/ay',growthYr:'Büyüme/yıl',infYr:'Enflasyon/yıl',link:'Bağla',starts:'Başlangıç',ends:'Bitiş',when:'Ne zaman',nameAsset:'Ad / Varlık',apprDepr:'Değerl./Amo.',sell:'Sat',buy:'Al',buyAsset:'Varlık al',moneyIn:'Gelen para',moneyOut:'Giden para',invReturns:'Yatırım getirileri',returns:'getiri',incomeTag:'gelir',soldTag:'satıldı',boughtTag:'alındı',spentTag:'harcandı',ownedTag:'sahip',liqAssets:'Likit varlıklar',illAssets:'Likit olmayan varlıklar',by:'Tarihine kadar',debt:'Borç',debtTag:'borç',balance:'Bakiye',rate:'Oran',pmtMo:'Ödeme/ay',debtRemain:'kalan',debts:'Borçlar',loanOut:'Borç ver',loanOutTag:'alacak',receivables:'Alacaklar',household:'Hane',kid1:'+1 çocuk',kid2:'+2 çocuk',kid3:'+3 çocuk',kid4:'+4 çocuk',yourTax:'Mevcut vergi oranınız',incomeAfterTax:'gelir {inc}/ay → {aft}/ay vergi sonrası',canAfford:'Yaşanabilir',cantAfford:'Yaşanamaz',affordLine:'karşılanabilirlik sınırı',afterTaxInc:'Vergi sonrası gelir',taxSavings:'Vergi tasarrufu',taxIncrease:'Vergi artışı',netSurplus:'Net fazla',savingsRate:'Tasarruf oranı',deficit:'Açık',localInf:'Yerel enflasyon',sameTax:'aynı',estimates:'Tahminler. Vergi = brüt gelir üzerinden efektif oran. Fazla = vergi sonrası gelir − yerel maliyetler.'},
ar:{pillars:'الثروة · التوقعات · الانتقال',relocHd:'أين يمكنك العيش؟',liqHd:'أصول سائلة',illHd:'أصول غير سائلة',revHd:'الدخل الشهري',costHd:'تكاليف المعيشة الشهرية',ievHd:'أحداث الدخل',eevHd:'أحداث النفقات',liqHint:'كل أصل ينمو بمعدله الخاص. الحساب <b>الرئيسي</b> يستقبل كل الدخل. المصروفات تُخصم أولاً من الحساب الرئيسي — إذا نفد، تنتقل إلى الأصل التالي.',illHint:'عقارات، مركبات — أصول يصعب بيعها بسرعة.',ievHint:'دخل لمرة واحدة أو بيع أصل.',eevHint:'نفقة لمرة واحدة أو شراء أصل.',none:'لا يوجد',now:'الآن',inMo:'خلال {m} شهر',inYr:'خلال {y} سنة',inYrMo:'خلال {y} سنة {m} شهر',moS:'ش',yrS:'س',curNet:'صافي الثروة الحالي',netIn:'صافي الثروة في',liquid:'سائل',illiquid:'غير سائل',total:'الإجمالي',family:'الأسرة',taxRate:'معدل الضريبة',region:'المنطقة',afford:'مدن ميسورة',mo:'/شهر',rent:'إيجار',food:'طعام',transport:'مواصلات',util:'مرافق',health:'صحة',other:'أخرى',tax:'ضريبة',inf:'تضخم',primary:'رئيسي',add:'+ إضافة',del:'×',name:'الاسم',value:'القيمة',returnRate:'العائد%',appRate:'التقدير%',amount:'المبلغ',from:'من',to:'إلى',growth:'النمو%',linked:'ربط',type:'النوع',date:'التاريخ',sell:'بيع أصل',cash:'نقد',expense:'مصروف',buy:'شراء أصل',solo:'فردي',couple:'زوجين',returnYr:'العائد/سنة',appYr:'التقدير/سنة',perMo:'$/شهر',growthYr:'النمو/سنة',infYr:'التضخم/سنة',link:'ربط',starts:'بداية',ends:'نهاية',when:'متى',nameAsset:'الاسم / الأصل',apprDepr:'تقدير/إهلاك',sell:'بيع',buy:'شراء',buyAsset:'شراء أصل',moneyIn:'الأموال الواردة',moneyOut:'الأموال الصادرة',invReturns:'عوائد الاستثمار',returns:'عوائد',incomeTag:'دخل',soldTag:'مُباع',boughtTag:'مُشترى',spentTag:'مُنفق',ownedTag:'مملوك',liqAssets:'أصول سائلة',illAssets:'أصول غير سائلة',by:'بحلول',debt:'دين',debtTag:'دين',balance:'الرصيد',rate:'الفائدة',pmtMo:'الدفعة/شهر',debtRemain:'المتبقي',debts:'الديون',loanOut:'إقراض',loanOutTag:'مستحق',receivables:'المستحقات',household:'الأسرة',kid1:'+1 طفل',kid2:'+2 أطفال',kid3:'+3 أطفال',kid4:'+4 أطفال',yourTax:'معدل الضريبة الحالي',incomeAfterTax:'الدخل {inc}/شهر → {aft}/شهر بعد الضريبة',canAfford:'يمكنك العيش',cantAfford:'لا يمكنك العيش',affordLine:'خط القدرة المالية',afterTaxInc:'الدخل بعد الضريبة',taxSavings:'توفير ضريبي',taxIncrease:'زيادة ضريبية',netSurplus:'الفائض الصافي',savingsRate:'معدل الادخار',deficit:'عجز',localInf:'التضخم المحلي',sameTax:'نفسه',estimates:'تقديرات. الضريبة = المعدل الفعلي على الدخل الإجمالي. الفائض = الدخل بعد الضريبة − التكاليف المحلية.'},
hi:{pillars:'संपत्ति · पूर्वानुमान · स्थानांतरण',relocHd:'आप कहाँ रह सकते हैं?',liqHd:'तरल संपत्ति',illHd:'अतरल संपत्ति',revHd:'मासिक आय',costHd:'मासिक जीवन लागत',ievHd:'आय घटनाएँ',eevHd:'व्यय घटनाएँ',liqHint:'प्रत्येक संपत्ति अपनी दर से बढ़ती है। <b>प्राथमिक</b> खाता सभी आय प्राप्त करता है। खर्च पहले प्राथमिक खाते से काटे जाते हैं — यदि समाप्त हो जाए, तो अगली संपत्ति पर जाते हैं।',illHint:'अचल संपत्ति, वाहन — जल्दी बेचना कठिन।',ievHint:'एकमुश्त आय या संपत्ति बिक्री।',eevHint:'एकमुश्त खर्च या संपत्ति खरीद।',none:'कोई नहीं',now:'अभी',inMo:'{m} महीने में',inYr:'{y} साल में',inYrMo:'{y} साल {m} महीने में',moS:'म',yrS:'व',curNet:'वर्तमान कुल संपत्ति',netIn:'कुल संपत्ति',liquid:'तरल',illiquid:'अतरल',total:'कुल',family:'परिवार',taxRate:'कर दर',region:'क्षेत्र',afford:'किफायती शहर',mo:'/माह',rent:'किराया',food:'भोजन',transport:'परिवहन',util:'उपयोगिताएँ',health:'स्वास्थ्य',other:'अन्य',tax:'कर',inf:'मुद्रास्फीति',primary:'प्राथमिक',add:'+ जोड़ें',del:'×',name:'नाम',value:'मूल्य',returnRate:'रिटर्न%',appRate:'मूल्यवृद्धि%',amount:'राशि',from:'से',to:'तक',growth:'वृद्धि%',linked:'लिंक',type:'प्रकार',date:'तारीख',sell:'संपत्ति बेचें',cash:'नकद',expense:'खर्च',buy:'संपत्ति खरीदें',solo:'अकेला',couple:'जोड़ा',returnYr:'रिटर्न/वर्ष',appYr:'मूल्यवृद्धि/वर्ष',perMo:'$/माह',growthYr:'वृद्धि/वर्ष',infYr:'मुद्रास्फीति/वर्ष',link:'लिंक',starts:'शुरू',ends:'अंत',when:'कब',nameAsset:'नाम / संपत्ति',apprDepr:'मूल्यवृद्धि/ह्रास',sell:'बेचें',buy:'खरीदें',buyAsset:'संपत्ति खरीदें',moneyIn:'आय',moneyOut:'व्यय',invReturns:'निवेश रिटर्न',returns:'रिटर्न',incomeTag:'आय',soldTag:'बेचा',boughtTag:'खरीदा',spentTag:'खर्च',ownedTag:'स्वामित्व',liqAssets:'तरल संपत्ति',illAssets:'अतरल संपत्ति',by:'तक',debt:'ऋण',debtTag:'ऋण',balance:'शेष',rate:'दर',pmtMo:'भुगतान/माह',debtRemain:'शेष',debts:'ऋण',loanOut:'उधार',loanOutTag:'प्राप्य',receivables:'प्राप्य राशि',household:'परिवार',kid1:'+1 बच्चा',kid2:'+2 बच्चे',kid3:'+3 बच्चे',kid4:'+4 बच्चे',yourTax:'आपकी वर्तमान कर दर',incomeAfterTax:'आय {inc}/माह → {aft}/माह कर के बाद',canAfford:'किफायती',cantAfford:'महंगा',affordLine:'किफायती सीमा',afterTaxInc:'कर-पश्चात आय',taxSavings:'कर बचत',taxIncrease:'कर वृद्धि',netSurplus:'शुद्ध अधिशेष',savingsRate:'बचत दर',deficit:'घाटा',localInf:'स्थानीय मुद्रास्फीति',sameTax:'समान',estimates:'अनुमान। कर = सकल आय पर प्रभावी दर। अधिशेष = कर-पश्चात आय − स्थानीय लागत।'},
ru:{pillars:'Капитал · Прогноз · Переезд',relocHd:'Где вы можете жить?',liqHd:'Ликвидные активы',illHd:'Неликвидные активы',revHd:'Ежемесячный доход',costHd:'Ежемесячные расходы',ievHd:'Разовые доходы',eevHd:'Разовые расходы',liqHint:'Каждый актив растёт по своей ставке. <b>Основной</b> счёт получает весь доход. Расходы списываются сначала с основного счёта — если он исчерпан, списание переходит на следующий актив.',illHint:'Недвижимость, транспорт — то, что сложно быстро продать.',ievHint:'Разовый доход или продажа актива.',eevHint:'Разовый расход или покупка актива.',none:'Пока нет',now:'сейчас',inMo:'через {m} мес.',inYr:'через {y} г.',inYrMo:'через {y} г. {m} мес.',moS:'м',yrS:'г',curNet:'Текущий капитал',netIn:'Капитал через',liquid:'Ликвидный',illiquid:'Неликвидный',total:'Итого',family:'Семья',taxRate:'Ваша ставка налога',region:'Регион',afford:'доступных городов',mo:'/мес.',rent:'Аренда',food:'Еда',transport:'Транспорт',util:'Коммунальные',health:'Здоровье',other:'Другое',tax:'Налог',inf:'Инфляция',primary:'ОСНОВНОЙ',add:'+ Добавить',del:'×',name:'Название',value:'Стоимость',returnRate:'Доход %',appRate:'Рост %',amount:'Сумма',from:'С',to:'По',growth:'Рост %',linked:'Связать',type:'Тип',date:'Дата',sell:'Продать актив',cash:'Наличные',expense:'Расход',buy:'Купить актив',solo:'Один',couple:'Пара',returnYr:'Доход/год',appYr:'Рост/год',perMo:'$/мес.',growthYr:'Рост/год',infYr:'Инфляция/год',link:'Связать',starts:'Начало',ends:'Конец',when:'Когда',nameAsset:'Название / Актив',apprDepr:'Рост/Ам.',sell:'Продать',buy:'Купить',buyAsset:'Купить актив',moneyIn:'Поступления',moneyOut:'Расходы',invReturns:'Доход от инвестиций',returns:'доход',incomeTag:'доход',soldTag:'продано',boughtTag:'куплено',spentTag:'потрачено',ownedTag:'в собственности',liqAssets:'Ликвидные активы',illAssets:'Неликвидные активы',by:'К',debt:'Долг',debtTag:'долг',balance:'Остаток',rate:'Ставка',pmtMo:'Платёж/мес.',debtRemain:'остаток',debts:'Долги',loanOut:'Займ',loanOutTag:'дебитор',receivables:'Дебиторская',household:'Семья',kid1:'+1 ребёнок',kid2:'+2 детей',kid3:'+3 детей',kid4:'+4 детей',yourTax:'Ваш налог',incomeAfterTax:'доход {inc}/мес. → {aft}/мес. после налогов',canAfford:'Доступно',cantAfford:'Недоступно',affordLine:'граница доступности',afterTaxInc:'Доход после налогов',taxSavings:'Экономия на налогах',taxIncrease:'Рост налогов',netSurplus:'Чистый остаток',savingsRate:'Норма сбережений',deficit:'Дефицит',localInf:'Местная инфляция',sameTax:'одинаково',estimates:'Оценки. Налог = эффективная ставка на валовой доход. Остаток = доход после налогов − местные расходы.'},
ka:{pillars:'კაპიტალი · პროგნოზი · გადასახლება',relocHd:'სად შეგიძლიათ ცხოვრება?',liqHd:'ლიკვიდური აქტივები',illHd:'არალიკვიდური აქტივები',revHd:'ყოველთვიური შემოსავალი',costHd:'ყოველთვიური ხარჯები',ievHd:'შემოსავლის მოვლენები',eevHd:'ხარჯის მოვლენები',liqHint:'თითოეული აქტივი იზრდება საკუთარი განაკვეთით. <b>მთავარი</b> ანგარიში იღებს ყველა შემოსავალს. ხარჯები ჯერ მთავარი ანგარიშიდან იჭრება — თუ ამოიწურა, გადადის შემდეგ აქტივზე.',illHint:'უძრავი ქონება, ტრანსპორტი.',ievHint:'ერთჯერადი შემოსავალი ან აქტივის გაყიდვა.',eevHint:'ერთჯერადი ხარჯი ან აქტივის შეძენა.',none:'ჯერ არ არის',now:'ახლა',inMo:'{m} თვეში',inYr:'{y} წელში',inYrMo:'{y} წ. {m} თვეში',moS:'თ',yrS:'წ',curNet:'მიმდინარე კაპიტალი',netIn:'კაპიტალი',liquid:'ლიკვიდური',illiquid:'არალიკვიდური',total:'ჯამი',family:'ოჯახი',taxRate:'გადასახადის განაკვეთი',region:'რეგიონი',afford:'ხელმისაწვდომი ქალაქი',mo:'/თვე',rent:'ქირა',food:'საკვები',transport:'ტრანსპორტი',util:'კომუნალური',health:'ჯანმრთელობა',other:'სხვა',tax:'გადასახადი',inf:'ინფლაცია',primary:'მთავარი',add:'+ დამატება',del:'×',name:'სახელი',value:'ღირებულება',returnRate:'შემოსავალი%',appRate:'ზრდა%',amount:'თანხა',from:'დან',to:'მდე',growth:'ზრდა%',linked:'დაკავშირება',type:'ტიპი',date:'თარიღი',sell:'აქტივის გაყიდვა',cash:'ნაღდი',expense:'ხარჯი',buy:'აქტივის ყიდვა',solo:'მარტო',couple:'წყვილი',returnYr:'შემოსავალი/წ.',appYr:'ზრდა/წ.',perMo:'$/თვე',growthYr:'ზრდა/წ.',infYr:'ინფლაცია/წ.',link:'დაკავშირება',starts:'დაწყება',ends:'დასრულება',when:'როდის',nameAsset:'სახელი / აქტივი',apprDepr:'ზრდა/კლება',sell:'გაყიდვა',buy:'ყიდვა',buyAsset:'აქტივის ყიდვა',moneyIn:'შემოსავალი',moneyOut:'გასავალი',invReturns:'საინვესტიციო შემოსავალი',returns:'შემოსავალი',incomeTag:'შემოსავალი',soldTag:'გაყიდული',boughtTag:'ნაყიდი',spentTag:'დახარჯული',ownedTag:'საკუთრებაში',liqAssets:'ლიკვიდური აქტივები',illAssets:'არალიკვიდური აქტივები',by:'მდე',debt:'ვალი',debtTag:'ვალი',balance:'ნაშთი',rate:'განაკვეთი',pmtMo:'გადახდა/თვე',debtRemain:'დარჩენილი',debts:'ვალები',loanOut:'სესხი',loanOutTag:'მისაღები',receivables:'მისაღები თანხები',household:'ოჯახი',kid1:'+1 შვილი',kid2:'+2 შვილი',kid3:'+3 შვილი',kid4:'+4 შვილი',yourTax:'თქვენი გადასახადი',incomeAfterTax:'შემოსავალი {inc}/თვე → {aft}/თვე გადასახადის შემდეგ',canAfford:'ხელმისაწვდომი',cantAfford:'მიუწვდომელი',affordLine:'ხელმისაწვდომობის ზღვარი',afterTaxInc:'შემოსავალი გადასახადის შემდეგ',taxSavings:'საგადასახადო დანაზოგი',taxIncrease:'გადასახადის ზრდა',netSurplus:'წმინდა ნაშთი',savingsRate:'დანაზოგის მაჩვენებელი',deficit:'დეფიციტი',localInf:'ადგილობრივი ინფლაცია',sameTax:'იგივე',estimates:'შეფასებები. გადასახადი = ეფექტური განაკვეთი მთლიან შემოსავალზე. ნაშთი = შემოსავალი გადასახადის შემდეგ − ადგილობრივი ხარჯები.'},
uk:{pillars:'Капітал · Прогноз · Переїзд',relocHd:'Де ви можете жити?',liqHd:'Ліквідні активи',illHd:'Неліквідні активи',revHd:'Щомісячний дохід',costHd:'Щомісячні витрати',ievHd:'Разові доходи',eevHd:'Разові витрати',liqHint:'Кожен актив зростає за своєю ставкою. <b>Основний</b> рахунок отримує весь дохід. Витрати спочатку списуються з основного рахунку — якщо він вичерпаний, переходять на наступний актив.',illHint:'Нерухомість, транспорт — те, що складно швидко продати.',ievHint:'Разовий дохід або продаж активу.',eevHint:'Разова витрата або купівля активу.',none:'Поки немає',now:'зараз',inMo:'через {m} міс.',inYr:'через {y} р.',inYrMo:'через {y} р. {m} міс.',moS:'м',yrS:'р',curNet:'Поточний капітал',netIn:'Капітал через',liquid:'Ліквідний',illiquid:'Неліквідний',total:'Всього',family:'Сім\'я',taxRate:'Ваша ставка податку',region:'Регіон',afford:'доступних міст',mo:'/міс.',rent:'Оренда',food:'Їжа',transport:'Транспорт',util:'Комунальні',health:'Здоров\'я',other:'Інше',tax:'Податок',inf:'Інфляція',primary:'ОСНОВНИЙ',add:'+ Додати',del:'×',name:'Назва',value:'Вартість',returnRate:'Дохід%',appRate:'Зростання%',amount:'Сума',from:'З',to:'По',growth:'Зростання%',linked:'Зв\'язати',type:'Тип',date:'Дата',sell:'Продати актив',cash:'Готівка',expense:'Витрата',buy:'Купити актив',solo:'Один',couple:'Пара',returnYr:'Дохід/рік',appYr:'Зрост./рік',perMo:'$/міс.',growthYr:'Зрост./рік',infYr:'Інфляція/рік',link:'Зв\'язати',starts:'Початок',ends:'Кінець',when:'Коли',nameAsset:'Назва / Актив',apprDepr:'Зрост./Ам.',sell:'Продати',buy:'Купити',buyAsset:'Купити актив',moneyIn:'Надходження',moneyOut:'Витрати',invReturns:'Інвестиційний дохід',returns:'дохід',incomeTag:'дохід',soldTag:'продано',boughtTag:'куплено',spentTag:'витрачено',ownedTag:'у власності',liqAssets:'Ліквідні активи',illAssets:'Неліквідні активи',by:'До',debt:'Борг',debtTag:'борг',balance:'Залишок',rate:'Ставка',pmtMo:'Платіж/міс.',debtRemain:'залишок',debts:'Борги',loanOut:'Позика',loanOutTag:'дебітор',receivables:'Дебіторська',household:'Сім\'я',kid1:'+1 дитина',kid2:'+2 дітей',kid3:'+3 дітей',kid4:'+4 дітей',yourTax:'Ваш податок',incomeAfterTax:'дохід {inc}/міс. → {aft}/міс. після податків',canAfford:'Доступно',cantAfford:'Недоступно',affordLine:'межа доступності',afterTaxInc:'Дохід після податків',taxSavings:'Економія на податках',taxIncrease:'Зростання податків',netSurplus:'Чистий залишок',savingsRate:'Норма заощаджень',deficit:'Дефіцит',localInf:'Місцева інфляція',sameTax:'однаково',estimates:'Оцінки. Податок = ефективна ставка на валовий дохід. Залишок = дохід після податків − місцеві витрати.'}
};
// Fallback to English for unsupported languages
const T=I18N[LANG]||I18N.en;
export function t(key){return T[key]||I18N.en[key]||key}
// Set HTML lang attribute
if(LANG!=='en')document.documentElement.lang=LANG;
// RTL support for Arabic
if(LANG==='ar')document.documentElement.dir='rtl';

// Seed data translations
export const SEED={
en:{chk:'Checking account',emf:'Emergency fund (HYSA)',ret:'401(k)',brk:'Brokerage (index funds)',home:'Home (suburb)',car:'Honda CR-V 2022',sal:'Salary (after tax)',side:'Side income / freelance',mort:'Mortgage payment',groc:'Groceries',carPay:'Car payment + insurance',util:'Utilities',health:'Health insurance (copays)',gas:'Gas & transport',subs:'Subscriptions & phone',dine:'Dining out & entertainment',misc:'Misc / personal',taxRef:'Tax refund',bonus:'Annual bonus',vac:'Family vacation',repair:'Home repair (roof)',reno:'Kitchen renovation'},
es:{chk:'Cuenta corriente',emf:'Fondo de emergencia',ret:'Plan de pensiones',brk:'Fondos indexados',home:'Vivienda',car:'Coche',sal:'Salario (neto)',side:'Ingresos extra / freelance',mort:'Hipoteca',groc:'Supermercado',carPay:'Coche + seguro',util:'Suministros',health:'Seguro médico',gas:'Gasolina y transporte',subs:'Suscripciones y móvil',dine:'Restaurantes y ocio',misc:'Varios / personal',taxRef:'Devolución de impuestos',bonus:'Bonus anual',vac:'Vacaciones familiares',repair:'Reparación del hogar',reno:'Reforma de cocina'},
fr:{chk:'Compte courant',emf:'Fonds d\'urgence',ret:'Plan épargne retraite',brk:'Fonds indiciels',home:'Résidence principale',car:'Voiture',sal:'Salaire (net)',side:'Revenus complémentaires',mort:'Crédit immobilier',groc:'Courses alimentaires',carPay:'Voiture + assurance',util:'Charges',health:'Mutuelle santé',gas:'Essence et transport',subs:'Abonnements et téléphone',dine:'Restaurants et sorties',misc:'Divers / personnel',taxRef:'Remboursement d\'impôts',bonus:'Prime annuelle',vac:'Vacances en famille',repair:'Travaux maison',reno:'Rénovation cuisine'},
de:{chk:'Girokonto',emf:'Notgroschen (Tagesgeld)',ret:'Altersvorsorge',brk:'ETF-Depot',home:'Eigenheim',car:'Auto',sal:'Gehalt (netto)',side:'Nebeneinkommen / Freelance',mort:'Hypothek',groc:'Lebensmittel',carPay:'Auto + Versicherung',util:'Nebenkosten',health:'Krankenversicherung',gas:'Benzin & Transport',subs:'Abos & Handy',dine:'Essen gehen & Freizeit',misc:'Sonstiges',taxRef:'Steuererstattung',bonus:'Jahresbonus',vac:'Familienurlaub',repair:'Hausreparatur',reno:'Küchenrenovierung'},
pt:{chk:'Conta corrente',emf:'Fundo de emergência',ret:'Previdência privada',brk:'Fundos de investimento',home:'Imóvel',car:'Carro',sal:'Salário (líquido)',side:'Renda extra / freelance',mort:'Financiamento imobiliário',groc:'Supermercado',carPay:'Carro + seguro',util:'Contas de luz/água',health:'Plano de saúde',gas:'Combustível e transporte',subs:'Assinaturas e celular',dine:'Restaurantes e lazer',misc:'Diversos / pessoal',taxRef:'Restituição de imposto',bonus:'Bônus anual',vac:'Férias em família',repair:'Reforma da casa',reno:'Reforma da cozinha'},
ja:{chk:'普通預金',emf:'緊急資金',ret:'確定拠出年金',brk:'証券口座（インデックス）',home:'自宅',car:'車',sal:'給与（手取り）',side:'副業・フリーランス',mort:'住宅ローン',groc:'食料品',carPay:'車両費・保険',util:'光熱費',health:'健康保険',gas:'ガソリン・交通費',subs:'サブスク・通信費',dine:'外食・娯楽',misc:'雑費',taxRef:'確定申告還付',bonus:'年間ボーナス',vac:'家族旅行',repair:'住宅修繕',reno:'キッチンリフォーム'},
zh:{chk:'活期存款',emf:'应急基金',ret:'养老金账户',brk:'证券账户（指数基金）',home:'住房',car:'汽车',sal:'工资（税后）',side:'副业收入',mort:'房贷',groc:'食品杂货',carPay:'车贷+保险',util:'水电费',health:'医疗保险',gas:'交通费',subs:'订阅和手机',dine:'外出就餐和娱乐',misc:'杂项',taxRef:'退税',bonus:'年终奖',vac:'家庭度假',repair:'房屋维修',reno:'厨房装修'},
ko:{chk:'입출금 계좌',emf:'비상금',ret:'퇴직연금',brk:'증권 계좌 (인덱스)',home:'주택',car:'자동차',sal:'급여 (세후)',side:'부업 / 프리랜서',mort:'주택담보대출',groc:'식료품',carPay:'차량비 + 보험',util:'공과금',health:'건강보험',gas:'교통비',subs:'구독 및 통신',dine:'외식 및 여가',misc:'기타',taxRef:'세금 환급',bonus:'연간 보너스',vac:'가족 여행',repair:'집수리',reno:'주방 리모델링'},
ru:{chk:'Текущий счёт',emf:'Резервный фонд',ret:'Пенсионный счёт',brk:'Брокерский счёт (индексы)',home:'Жильё',car:'Автомобиль',sal:'Зарплата (после налогов)',side:'Подработка / фриланс',mort:'Ипотека',groc:'Продукты',carPay:'Авто + страховка',util:'Коммунальные',health:'Медстраховка',gas:'Бензин и транспорт',subs:'Подписки и связь',dine:'Рестораны и развлечения',misc:'Прочее',taxRef:'Возврат налога',bonus:'Годовая премия',vac:'Семейный отпуск',repair:'Ремонт дома',reno:'Ремонт кухни'},
ka:{chk:'მიმდინარე ანგარიში',emf:'საგანგებო ფონდი',ret:'საპენსიო ანგარიში',brk:'საინვესტიციო ანგარიში',home:'სახლი',car:'მანქანა',sal:'ხელფასი (გადასახადის შემდეგ)',side:'დამატებითი შემოსავალი',mort:'იპოთეკა',groc:'სურსათი',carPay:'მანქანა + დაზღვევა',util:'კომუნალური',health:'ჯანმრთელობის დაზღვევა',gas:'ბენზინი და ტრანსპორტი',subs:'გამოწერები და ტელეფონი',dine:'რესტორნები და გართობა',misc:'სხვა',taxRef:'გადასახადის დაბრუნება',bonus:'წლიური ბონუსი',vac:'საოჯახო შვებულება',repair:'სახლის შეკეთება',reno:'სამზარეულოს რემონტი'},
tr:{chk:'Vadesiz hesap',emf:'Acil durum fonu',ret:'Emeklilik hesabı',brk:'Yatırım hesabı (endeks)',home:'Ev',car:'Araba',sal:'Maaş (net)',side:'Ek gelir / serbest',mort:'Konut kredisi',groc:'Market alışverişi',carPay:'Araba + sigorta',util:'Faturalar',health:'Sağlık sigortası',gas:'Benzin ve ulaşım',subs:'Abonelikler ve telefon',dine:'Dışarıda yemek ve eğlence',misc:'Çeşitli',taxRef:'Vergi iadesi',bonus:'Yıllık prim',vac:'Aile tatili',repair:'Ev tamiri',reno:'Mutfak yenileme'},
ar:{chk:'حساب جاري',emf:'صندوق طوارئ',ret:'حساب تقاعد',brk:'حساب استثمار',home:'منزل',car:'سيارة',sal:'راتب (بعد الضريبة)',side:'دخل إضافي',mort:'قسط المنزل',groc:'بقالة',carPay:'سيارة + تأمين',util:'مرافق',health:'تأمين صحي',gas:'وقود ومواصلات',subs:'اشتراكات وهاتف',dine:'مطاعم وترفيه',misc:'متفرقات',taxRef:'استرداد ضريبي',bonus:'مكافأة سنوية',vac:'إجازة عائلية',repair:'صيانة المنزل',reno:'تجديد المطبخ'},
hi:{chk:'चालू खाता',emf:'आपातकालीन निधि',ret:'पेंशन खाता',brk:'निवेश खाता (इंडेक्स)',home:'घर',car:'कार',sal:'वेतन (कर के बाद)',side:'अतिरिक्त आय / फ्रीलांस',mort:'गृह ऋण',groc:'किराना',carPay:'कार + बीमा',util:'उपयोगिताएँ',health:'स्वास्थ्य बीमा',gas:'ईंधन और परिवहन',subs:'सदस्यता और फोन',dine:'बाहर खाना और मनोरंजन',misc:'विविध',taxRef:'कर वापसी',bonus:'वार्षिक बोनस',vac:'पारिवारिक छुट्टी',repair:'घर की मरम्मत',reno:'रसोई नवीकरण'},
uk:{chk:'Поточний рахунок',emf:'Резервний фонд',ret:'Пенсійний рахунок',brk:'Брокерський рахунок',home:'Житло',car:'Автомобіль',sal:'Зарплата (після податків)',side:'Підробіток / фріланс',mort:'Іпотека',groc:'Продукти',carPay:'Авто + страховка',util:'Комунальні',health:'Медстрахування',gas:'Пальне і транспорт',subs:'Підписки і зв\'язок',dine:'Ресторани і розваги',misc:'Інше',taxRef:'Повернення податку',bonus:'Річна премія',vac:'Сімейна відпустка',repair:'Ремонт дому',reno:'Ремонт кухні'}
};
export const S=SEED[LANG]||SEED.en;
